# The root directory of the project
root = "."

# The temporary directory where Air will store its temporary files
tmp_dir = "tmp"

[build] # The build configuration

# The name of the binary file to be generated after building the project
bin = "main"

# The command to build the project
cmd = "go build -o {{.Output}} {{.Input}}"

# Specifies the directories to be excluded from monitoring for changes
exclude = ["tmp/*", "client/*"]

# Specifies the file patterns to be included for monitoring
include = ["**/*.go"]

# Specifies the files or directories to be ignored when triggering build
ignore = ["tmp/*"]
